name: namcap

on:
  push:
  workflow_dispatch:

jobs:
  namcap:
    runs-on: ubuntu-24.04-arm
    container:
     image: ghcr.io/aarchd/aarchd:latest
     options: --privileged
    permissions:
      contents: write
    steps:
      - name: Setup
        run: |
          mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
          echo "Server = http://ca.us.mirror.archlinuxarm.org/aarch64/\$repo" | tee "/etc/pacman.d/mirrorlist"
          pacman -Syyu git namcap libarchive --noconfirm --needed
          pacman-key --init
          pacman-key --populate archlinuxarm
          pacman-key --recv-key 6290731A5B773E16 --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 6290731A5B773E16

      - name: Checkout
        uses: actions/checkout@v4

      - name: namcap
        run: |
          cd PKGS/
          for pkg in *.pkg.tar.zst; do
            echo ""
            echo -e "\033[1;34m=====================================\033[0m"
            if [[ "$pkg" == *adaptation-hybris* ]]; then
              echo -e "\033[1;33mSkipping package (adaptation-hybris match):\033[0m $pkg"
              continue
            fi
            echo -e "\033[1;32mInstalling:\033[0m $pkg"
            pacman -U --noconfirm "$pkg"
            echo -e "\033[1;34m=====================================\033[0m"
            echo -e "\033[1;32mRunning namcap on:\033[0m $pkg"
            echo -e "\033[1;34m=====================================\033[0m"
            namcap -e shebangdepends,elfgnurelro,elfnoshstk "$pkg"
            echo -e "\033[1;34m=====================================\033[0m"
            echo -e "\033[1;32mRemoving:\033[0m $pkg"
            pkgname="$(bsdtar -xOf "$pkg" .PKGINFO | grep pkgname | cut -d' ' -f3)"
            if [[ "$pkgname" != "aarchd-keyring" && "$pkgname" != "aarchd-mirrorlist" && "$pkgname" != "pacman" ]]; then
              echo -e "\033[1;34m=====================================\033[0m"
              echo -e "\033[1;32mRemoving:\033[0m $pkgname"
              pacman -Rns --noconfirm "$pkgname"
            else
              echo -e "\033[1;33mSkipping removal of protected package:\033[0m $pkgname"
            fi
            echo ""
          done
